export enum StatusAspirasi {
  MENUNGGU = "MENUNGGU",
  DIPROSES = "DIPROSES",
  SELESAI = "SELESAI",
  DITOLAK = "DITOLAK",
}

export enum KategoriEnum {
  KEBERSIHAN = "KEBERSIHAN",
  KEAMANAN = "KEAMANAN",
  FASILITAS_BELAJAR = "FASILITAS_BELAJAR",
  INFRASTRUKTUR = "INFRASTRUKTUR",
  LAINNYA = "LAINNYA",
}
